{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
<label for="ContentClass_xrowmultibinary_max_filesize_{$class_attribute.id}">{'Max file size'|i18n( 'design/standard/class/datatype' )}:</label>
<input type="text" id="ContentClass_xrowmultibinary_max_filesize_{$class_attribute.id}" name="ContentClass_xrowmultibinary_max_filesize_{$class_attribute.id}" value="{$class_attribute.data_int1}" size="5" maxlength="5" />&nbsp;<span class="normal">MB</span>
</div>
<div class="block">
<label for="ContentClass_xrowmultibinary_max_number_of_files_{$class_attribute.id}">{'Max number of files'|i18n( 'design/standard/class/datatype' )}:</label>
<input type="text" id="ContentClass_xrowmultibinary_max_number_of_files_{$class_attribute.id}" name="ContentClass_xrowmultibinary_max_number_of_files_{$class_attribute.id}" value="{$class_attribute.data_int2}" size="5" maxlength="5" />
</div>